### PR TITLE
Info about blocking subscriptions

### PR DESCRIPTION
**Pull request by vbagirov**

### CODE REVIEW

**Comment by ameshkov** [comment]
That's just not enough. We should rework this document, add the app screenshots there.

**Comment by vbagirov** [comment]
@ameshkov I know that's not enough, that's why you are not among the reviewers :) This is a work in progress, just the first iteration.

**Comment by vbagirov** [comment]
@ameshkov we need to merge this PR now (for iOS beta purposes), we'll come back later and finish reworking the article.

**Comment by ameshkov** [comment]
It's unnecessary for beta

**Comment by zebrum** [comment]
I needed it for this task to be done:  https://github.com/AdguardTeam/AdguardForiOS/issues/574

**Comment by ameshkov** [comment]
@zebrum let's consider that task done when the whole article is reworked.

**Comment by zebrum** [comment]
uploaded some screenshots.

1. I think 'DNS filtering" part should go first. Also it needed some rephrasing in those sentences where system wide adblocking is mentioned.
2. The second part should be 'Subscriptions'.
3. 'Filtering log' part: add info about trackers detection. 
4. Should we add info about Widget?

**Pull request merged**
