### PR TITLE
dns-over-quic

### PR DESCRIPTION
**Pull request by pengelana**
add dns-over-quic

### CODE REVIEW

**Comment by ameshkov** [comment]
Oh, awesome!

@pengelana please use [this] to generate an SDNS link: https://dnscrypt.info/stamps

You just need to specify the hostname and proto there. You can use https://github.com/ameshkov/dnslookup to test the stamp.

**Comment by pengelana** [comment]
@ameshkov Thanks!

The SDNS:

`sdns://BAMAAAAAAAAAEjE3NC4xMzguMjkuMTc1Ojc4NAAMZG9oLnRpYXIuYXBw`

~~~
./dnslookup example.org sdns://BAMAAAAAAAAAEjE3NC4xMzguMjkuMTc1Ojc4NAAMZG9oLnRpYXIuYXBw
dnslookup undefined
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 39082
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.org.   IN       A

;; ANSWER SECTION:
example.org.    20804   IN      A       93.184.216.34

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 1232
~~~

**Comment by ameshkov** [comment]
@pengelana could you please update the PR accordingly? You should use an SDNS link in the "Add to AdGuard" link.

**Comment by ameshkov** [comment]
Thank you!

@vbagirov please mirror to other languages.

**Review by ameshkov — APPROVED** [review]

**Review by vbagirov — APPROVED** [review]

**Pull request merged**
