### PR TITLE
Create docs.tr.md

### PR DESCRIPTION
**Pull request by bkrucarci**
I translated the current English article to Turkish.

### CODE REVIEW

**Comment by ameshkov** [comment]
Hey @bkrucarci, thank you!

@vbagirov @vozersky guys, what's the minimum number of translated articles we need to add a new language to KB?

**Comment by bkrucarci** [comment]
@ameshkov I will continue to translate articles (in my free times)
Tell me how many articles do you need for Turkish?
Thanks

**Comment by vbagirov** [comment]
@bkrucarci I'd say at the very least the whole "General questions" category and "Overview" subcategories for all products should be translated completely to justify adding a new language.

Also worth mentioning taht it is quite easy to just add `tr` pages (like `https://kb.adguard.com/tr/`) but can take a while before we introduce a proper UI for switching between multiple languages.

**Comment by bkrucarci** [comment]
@vbagirov Can you please give me the links of the pages which you need in Turkish fro adding a new language?
https://github.com/AdguardTeam/AdguardKnowledgeBase/tree/master/pages
I will create a schedule to translate most important pages to less.

**Comment by vbagirov** [comment]
@bkrucarci all of these https://github.com/AdguardTeam/AdguardKnowledgeBase/tree/master/pages/02.general

Plus things like https://github.com/AdguardTeam/AdguardKnowledgeBase/tree/master/pages/03.windows/01.overview but also for all other products (03. - 09.). 

Plus https://github.com/AdguardTeam/AdguardKnowledgeBase/tree/master/pages/10.technical-support

**Comment by bkrucarci** [comment]
@vbagirov I will try my best on these pages. During the period, for possible questions, I will ask them under this thread. Thank you!

**Comment by ameshkov** [comment]
@bkrucarci it'd be better to push all the changes in a single pull request, just for order

**Comment by bkrucarci** [comment]
@ameshkov without clicking "Pull request", are my works saved?

**Comment by ameshkov** [comment]
> @ameshkov without clicking "Pull request", are my works saved?

Yes, everything is stored in your forked repo:
https://github.com/bkrucarci/AdguardKnowledgeBase

Check the branches there

**Comment by vbagirov** [comment]
We backlogged the idea of adding more languages to Knowledge base, so I'll have to close the PR.

**Pull request closed without merging**
