### PR TITLE
docs.en.md: `it's` -> `its` (x13), `subdomain` -> `subdomains` (x1)

### PR DESCRIPTION
**Pull request by contribucious**
# docs.en.md

- `it's` -> `its` (x13);
- `subdomain` -> `subdomains` (x1).
&nbsp;

**Related information:** https://dictionary.cambridge.org/grammar/british-grammar/it-s-or-its

### CODE REVIEW

**Comment by contribucious** [comment]
Hello @nataMai,

I would say … thank _you_ for all these changes. :thumbsup:

But … this was originally just a humble little modification by a non-native English speaking contributor. :octocat:

Therefore I can just confirm, from a technical point of view, that I personally don't see any error between the rules and the descriptions after your changes. :heavy_

**Comment by contribucious** [comment]
Hello @nataMai,
&nbsp;

I would say … thank _you_ for all these suggestions. :thumbsup:

But … this was originally just a humble little modification (mainly concerning a common mistake) by a contributor who doesn't have English as a mother tongue. :octocat:

Therefore I can only confirm, from a _technical point of view_, that I _personally_ don't see any error between the rules and their description after your changes`*`. :heavy_check_mark:
&nbsp;
<details>
<summary><del>Read more …</del>&nbsp;&nbsp;<strong>(But no longer valid though, see … next post.)</strong></summary>
&nbsp;

So … based on [this data](https://github.com/AdguardTeam/AdguardKnowledgeBase/graphs/contributors), as you seem to be the first committer of this repository @vbagirov, could you confirm that everything looks OK to you mainly from an _"English language" point of view_ and consistent with the whole (at least with each local context)? _Related to: use of present tense instead of future tense in some of these changes, not deviating too much from the Russian version, etc._

#### :arrow_right_hook: If so, I'll validate all @nataMai changes in a single commit and possibly try a few changes myself after that. And, therefore, rename this PR which becomes wider than expected. _(The name of the branch, `patch-2`, is already quite generic so already OK.)_
&nbsp;
___
##### :bulb: Personally, I like for example this idea of starting all rule descriptions simply with `this rule [present tense here]` instead of `a rule to` mixed with sometimes `this rule [future tense here]`. (After its modifications, there still seem to be 3 _related_ occurrences of `a rule to` on the page, which I can correct with your agreement @vbagirov, see the paragraph just below.) :thumbsup:

##### For example, for the sake of consistency, if we take this path for <code>###### `domain` and `~` examples</code> (cf. one of these changes / [KB section here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#domain)), we should take the same for <code>##### `app` and `~` examples</code> I would say (see [KB section here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#app-and-examples)). For the other two remaining places, namely <code>###### `domain` examples</code> and <code>##### `app` examples</code>, I actually think that leaving `a rule to` can however be considered there, as long as it remains consistent between the two.

###### :warning: However, concerning the alignment on this same principle, of the [unique presence of `a rule that […]`](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-examples-1) on the whole page among the various proposals, I am less convinced. Because it makes sense in this specific case: in the continuity of the previous rule `a simple rule, which […]`.

#### :arrow_right_hook: Open to any improvements, @vbagirov! :thumbsup:
</details>
&nbsp;
&nbsp;

___
`*` In fact … see next post, separated for clarity. Because it's more complicated than that. _(And sorry in advance for the length.)_

**Comment by contribucious** [comment]
# Regarding the _technical point of view_
&nbsp;

**After a more in-depth analysis and _long_ hours spent, I give up for my part**: a simple modification of the wording of the sentences — besides the fact that we must ensure to be consistent everywhere — can change meaning from a technical point of view _insidiously_.
&nbsp;

## Let's consider this part modified by you, @nataMai …
&nbsp;

### STATE BEFORE
> `domain` examples:
>
> `[$domain=~example.com]##.textad` - { hides **_a `div`_** } with a class `textad` at all domains, except `example.com` and its subdomains.

:arrow_right: As said in the two words before the colon, just above, this is therefore an _example_, descriptive of a random situation — i.e. if we are in a _given situation_ where we want to hide **_a known and popular `div` used by a specific marketing company almost everywhere on the Internet and which has for class `textad`_** on any domain except `[*.]example.com`, we will use that (kind of) rule.&nbsp;&nbsp; :heavy_exclamation_mark: _Kind of understanding: passive/relaxed mode._ :heavy_exclamation_mark:

:arrow_right_hook: In other words: it "hides a div", quickly, in a few characters (as desired … in the potential situation in which this dummy user would find himself) but it doesn't say that it couldn't hide other things instead (a span element having this class instead for example).
&nbsp;

### STATE BEFORE — Another _similar_ example (untouched by you currently) to better understand.
> `domain` examples:
>
> `[$domain=example.com]##.textad` — { hides **_a `div`_** } with a class `textad` at `example.com` and all subdomains.

:arrow_right: When we apply this current way of formulating rule descriptions to a rule targeting a _specific_ domain, like in this case, where we know even more, _for sure_, that the `.textad` is definitely a `div` (and that the risk of unintentionally impacting _another_ type of element _unfortunately having the same class_ is almost zero), the use of `.textad` instead of `div.textad`, _while_ talking about `div` in the rule description, is often used. My point is then even more relevant and probably more comprehensive. But I based myself initially on an example modified by you @nataMai (the rest, like this example, should however follow in a concern of consistency unfortunately).
&nbsp;

### STATE AFTER … _(your modification)_
> `domain` examples:
>
> `[$domain=~example.com]##.textad` - { **this rule hides `div` elements** } of the class `textad` for all domains, except `example.com` and its subdomains.

:arrow_right: Now look at how by starting with **`this rule [hides]`** you are instead trying to describe precisely what this rule does from a _theoretical_ point of view. Such a manual would.&nbsp;&nbsp; :heavy_exclamation_mark: _Kind of understanding: active mode._ :heavy_exclamation_mark:

:arrow_right_hook: But therefore, observe that the **_description is no longer valid_**. Indeed, from a _theoretical_ point of view — such as a description in a manual —, this rule **does not** "hide `div` elements of the class `textad`" but instead it hides "_elements_ of the class `textad`". _Any_ kind of element of the class `textad`: it can be `div`, `span`, etc. (or _even_ several of them in fact). Based on your update, the rule should then be changed to `[…]##div.textad` to continue to match your description!

:arrow_right_hook: Not to mention the fact that this implies changing it everywhere for good consistency (as in the examples of [`$path`](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#path) and many others).
&nbsp;
&nbsp;

#### :warning: This is just one example of how, based on this simple modification, a lot of rule descriptions in the examples need to be redesigned on the _2392 lines_ in the `docs.en.md` file today.
&nbsp;

### :arrow_right_hook: So, for everyone's sake, it would be wiser:
#### - for me, to click on the `Resolve conversation` button on each suggestion;
#### - for @vbagirov, to merge this simple PR and
#### - for you, @nataMai, to make a dedicated PR instead, where the implications can be discussed more fully and adequately.

### What do you two think? :octocat:

**Review by nataMai — APPROVED** [review]

**Comment by contribucious** [comment]
Hi @nataMai,
&nbsp;

LGTM :v: except one small thing:
&nbsp;

You changed this:
> * `example.org#?#div:has(> a[target="_blank"][rel="nofollow"])` — this rule will block all `div` elements that <strong>contain link as a child node</strong> with `[target="_blank"][rel="nofollow"]` attributes. The rule will only work for `example.org` and all it's subdomains.

by this:
> * `example.org#?#div:has(> a[target="_blank"][rel="nofollow"])` — this rule blocks all `div` elements <strong>containing a child node that has a link</strong> with the attributes `[target="_blank"][rel="nofollow"]`. The rule applies only to `example.org` and its subdomains.

:arrow_right_hook: The problem is in part <code>containing a child node that <strong><em>has</em></strong> a link [with the attributes…]</code>.
Which will typically be understood by most people as "that has a link _(element)_ [with the attributes…] WITHIN".
They may not immediately think of _link_ in the sense of the _href_ attribute, IMHO.

:arrow_right: To stay as close as possible to your phrasing, I would rectify this as follows: <code>containing a child node that <strong><em>is</em></strong> a link</code>.
Can be reworked of course but you get the idea.

###### **Related information:** https://developer.mozilla.org/en-US/docs/Web/CSS/:has

**Pull request merged**
