### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by eduardoaddad**
Add Brazilian Portuguese translation

### CODE REVIEW

**Comment by ameshkov** [comment]
@vbagirov @Dariamag we really, really need to move the KB content to Crowdin.

**Comment by eduardoaddad** [comment]
> @vbagirov @Dariamag we really, really need to move the KB content to Crowdin.

I agree with that point

In addition to making translation easier and more languages ​​supported

**Comment by Dariamag** [comment]
@ameshkov We will, next year! We need to rewrite some content to match the new structure. And then we will add the up-to-date KB to Crowdin

**Comment by vbagirov** [comment]
We backlogged the idea of adding more languages to Knowledge base, so I'll have to close the PR.

**Pull request closed without merging**
