### PR TITLE
:remove() -> `:remove()` (add backticks)

### PR DESCRIPTION
**Pull request by contribucious**
## Fixes made in both files

**[~] [3x]** :remove() -> `:remove()` (add backticks)
&nbsp;
&nbsp;

## Fixes required in `docs.en.md` only

**[~] [1x]** :remove() -> `:remove()` (add backticks)
##### :arrow_right_hook: _(In this file, the backticks were also missing in the table of contents.)_
&nbsp;

## Fixes required in `docs.ru.md` only

**[+] [1x]** Add a missing space before an existing `:remove()`.
##### :arrow_right_hook: _(Problem only present in this file.)_
&nbsp;
&nbsp;

#### :heavy_check_mark: Everything related to backticks regarding :remove() is fixed in these two files at the moment after this change.

### CODE REVIEW

**Review by nataMai — CHANGES_REQUESTED** [review]

**Comment by contribucious** [comment]
Hello @nataMai, :wave:
&nbsp;

By searching for _"Limited to work properly only"_ on the page, I found a 4th result, in the [pseudo-class `:remove()` section](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-remove-and-pseudo-property-remove) itself:
> Pseudo-class `:remove()` is limited to work properly only at the end of selector.

:arrow_right_hook: Are you OK with this sentence or does it need to be adapted as well to be in line with your changes (for potential consistency)?

###### Waiting for your answer before committing. :thumbsup:

**Comment by contribucious** [comment]
### Aside note

<details>
<summary>Show it …</summary>
&nbsp;

By the way, I totally understand that you take advantage of a contributor's sentence changes to directly improve them even more, but in my opinion it would be better to separate **two things**: 🙂

1. validating (or not) the slight modifications made by the latter;
2. make separate PRs (or commits directly since you have the rights) for any other changes not _directly_ related to the initial PR.

#### And this for 3 reasons:
1. Contributors may not have the technical or linguistic ability to understand your additional changes (and their implications) in order to validate them, knowing that this is done partly in their name (they are shown as "co-author").
2. This may discourage people who just want to make small changes (especially beginners or younger people), knowing that they will have to potentially study several issues in depth.
3. It deviates from the initial PR: the ideal is to stay on the famous [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) (one PR = one action and one direction, here for example adding backticks for ":remove()" throughout the English + Russian document). The name of the PR, the name of the branch, etc. is to be revised otherwise.<strong>`*`</strong>
  - ###### :bulb: Especially since "out-of-scope" changes may have to result in other changes to the file and the use of GitHub's "suggested changes" feature is currently limited — though perhaps that could change soon, see https://github.com/github/feedback/discussions/4452.

##### <strong>`*`</strong> This is how otherwise, in the case of my previous PR for example, we end up with `docs.en.md: it's -> its (x13), subdomain -> subdomains (x1) (#954)` appearing in the history when in the end, it has almost nothing to do with it. The rapid follow-up of the actions carried out and the immediate clarity become therefore affected when hovering over the [history](https://github.com/AdguardTeam/AdguardKnowledgeBase/commits/master) (and … even the icon to display the details doesn't always help, displaying for example in this case only a multitude of `Update 01.general/02.how-to-create-your-own-ad-filters/docs.en.md` which are not instantly meaningful).

This is just a (positive) tip, from ... a contributor. :v: :wink:
</details>

**Comment by nataMai** [comment]
Hi @contribucious,
Thank you so much for your input and suggestions! 
Yes, please update the fourth occurrence of "Limited to work properly only" to make it consistent with the changes.

**Comment by contribucious** [comment]
Done. :heavy_check_mark: :relaxed:
_(After checking the Russian version, I see it's already OK there — your new wording seems to come from there actually)._
&nbsp;
&nbsp;

##### On the other hand, not speaking Russian and having to use a translator, it seems that what I just committed:
> **Pseudo-class `:remove()` can be placed only at the end of a selector.**

##### corresponds well to:
> **Псевдо-класс `:remove()` может быть только в конце выражения.**

&nbsp;

##### But that your three identical modifications:
> **Can be placed only at the end of a selector, except for [pseudo-class `:remove()`](#remove-pseudos).**

##### don't correspond well to:
> **Может быть только в конце выражения, за исключением использования [псевдокласса `:remove()`](#remove-pseudos).**

&nbsp;

:arrow_right_hook: [This commit](https://github.com/AdguardTeam/AdguardKnowledgeBase/commit/6f66303e5c6f4a388110cbb63462f8136020085a) _(Aug 10, 2020)_ added the word `использования` and the sentence therefore seems effectively more understandable.
&nbsp;
&nbsp;

:bulb: Based on the translation of both `Google Translate` and `DeepL Translate`, it would look like this instead:
> **Can be placed only at the end of a selector, except when using the [pseudo-class `:remove()`](#remove-pseudos).**

&nbsp;
&nbsp;

What do you think, knowing that you speak Russian? 🙂
###### Just let me know if you would like me to make this change, before merging. :thumbsup:

**Comment by nataMai** [comment]
Hi @contribucious,
I suggest not relying on automated translation tools. Russian and English have different grammatical structures. Let English sound like English and Russian sound like Russian.

**Review by nataMai — APPROVED** [review]

**Comment by contribucious** [comment]
Hi @nataMai,

OK, perfect. :v: 🙂

**Pull request merged**
