### PR TITLE
docs.zh.md

### PR DESCRIPTION
**Pull request by shwunj**

### CODE REVIEW

**Comment by Dariamag** [comment]
@shwunj Thanks! Please rename the file to docs.zh.md

@DashaBu can you please review?

**Comment by shwunj** [comment]
> @shwunj谢谢！请将文件重命名为docs.zh.md
> 
> @DashaBu您可以复习吗？

I've done all the renaming

**Comment by Dariamag** [comment]
@shwunj sorry, but I missed one thing. It’s not enough to just rename the file. In this pull request you are changing the english file directly :( 
Instead we need to **create a new** “docs.zh.md” file in the direction that you are translating, and put your translation there. Like this: https://uploads.adguard.com/dariamag60f6j.png
For this pull request I have already created a new one: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/639

**Comment by shwunj** [comment]
> @shwunj对不起，但我错过了一件事。仅重命名文件是不够的。在此拉取请求中，您将直接更改英语文件:(
> 相反，我们需要按照您翻译的方向**创建一个新的** “ docs.zh.md”文件，然后将翻译内容放在此处。像这样：[https：// uploads .adguard.com / dariamag60f6j.png](https://uploads.adguard.com/dariamag60f6j.png)
> 对于此拉取请求，我已经创建了一个新请求：[＃639](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/639)

You look look this https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/642

**Comment by shwunj** [comment]
> @shwunj对不起，但我错过了一件事。仅重命名文件是不够的。在此拉取请求中，您将直接更改英语文件:(
> 相反，我们需要按照您翻译的方向**创建一个新的** “ docs.zh.md”文件，然后将翻译内容放在此处。像这样：[https：// uploads .adguard.com / dariamag60f6j.png](https://uploads.adguard.com/dariamag60f6j.png)
> 对于此拉取请求，我已经创建了一个新请求：[＃639](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/639)

To be honest, I don't know much about GitHub operations

**Pull request closed without merging**
