### PR TITLE
Added 'arapurayil' resolver

### PR DESCRIPTION
**Pull request by arapurayil**
Proposal to include resolvers maintained by me(arapurayil). Supports DoH, DoT and DNSCrypt protocols.

### CODE REVIEW

**Comment by ameshkov** [comment]
@vbagirov I am starting to think that we should have a special section for small personal DNS resolvers. We won't be able to monitor their availability and this should be clear to people who read that document.

**Comment by mHatsune** [comment]
> @vbagirov I am starting to think that we should have a special section for small personal DNS resolvers. We won't be able to monitor their availability and this should be clear to people who read that document.

@ameshkov  Put DNS providers IPs and domains to availability monitoring service or other own thing and do some html,css magic then display "Up or Down" status button (easy) or many days status in a row for each on KB static site.
Currently site template for DNS providers isn't quite good. you can scroll down to see later added tables.

**Comment by mHatsune** [comment]
https://servers.opennicproject.org/

image
image

**Comment by vbagirov** [comment]
Closing this PR due to #813

**Pull request closed without merging**
