### PR TITLE
Added my DNS server

### PR DESCRIPTION
**Pull request by DandelionSprout**
If there's anything about the server that you guys are wondering about, there's a 97% chance that it's answered by the Readme at https://github.com/DandelionSprout/adfilt/tree/master/Dandelion%20Sprout's%20Official%20DNS%20Server

### CODE REVIEW

**Comment by ameshkov** [comment]
@vbagirov ping

**Comment by DandelionSprout** [comment]
Doesn't seem like the requested review ever happened this time either.

**Comment by vbagirov** [comment]
@DandelionSprout 100% my fault. Ready to merge your PR, but you may want to add an explicit anchor first. I am not 100% sure `#dandelion-sprouts-official-dns-server` will work with just a header as it is now.

Please do that (or let me know that you don't want an anchor) and ping me, I hope I will react much quicker this time.

**Comment by DandelionSprout** [comment]
@vbagirov I at least *think* I've added an explicit anchor now. It took me some minutes to figure out what that phrase could mean.

**Review by vbagirov — APPROVED** [review]

**Comment by vbagirov** [comment]
@DandelionSprout yeah I should have been more specific. That's exactly what I meant, thank you.

**Comment by DandelionSprout** [comment]
Come to think of it, are there any time estimates for how often `kb.adguard.com` is synced with this GitHub repo? It doesn't seem on my end like *Dandelion Sprout's Official DNS Server* is on https://kb.adguard.com/en/general/dns-providers after 6 days.

**Comment by vbagirov** [comment]
@DandelionSprout there's no set time period, at least at the moment. I will see that it's updated today or tomorrow.

**Comment by DandelionSprout** [comment]
Just in case anyone go to this thread to look for status updates on my server instead of https://github.com/DandelionSprout/adfilt/tree/master/Dandelion%20Sprout's%20Official%20DNS%20Server:

I am aware that my main RaspPi server has been decommisioned (Possibly permanently) due to repeated and frequent problems with package managers uninstalling very critical packages during mass package updates, most recently its ability to connect to the internet and not just LAN.

I aim to have a 2-server setup based around Windows PCs ready for re-opening by the 19th of January.

**Pull request merged**
